"""Stati delle ConversationHandler."""

from __future__ import annotations

SANT_SILENZIO = 10
SANT_CREPUSCOLO = 11
SANT_COLONNE = 12
SANT_LIBRO = 13
SANT_CANDELA = 14
SANT_USCITA = 15
SANT_ESCI = 16

OPEN_WAIT_TEXT = 20
OPEN_CONFIRM = 21

ACT_WAIT_TEXT = 30
ACT_WAIT_VERIFY = 31
ACT_CONFIRM = 32

VEIL_CHOOSE = 40
VEIL_NOTE = 41

LABEL_WAIT = 50
LABEL_CONFIRM = 51
